name = "JCGEAgentInterface"
uuid = "0ceb7b1e-19fc-43b9-b3d5-2f4cf3d18128"
authors = ["Riccardo Boero <ribo@nilu.no>"]
version = "0.0.0"

[deps]
JCGECore = "9fb9d605-0ed3-4980-82c1-f0874844db5d"
JCGERuntime = "cc244198-1562-43f7-ad75-589e1d675269"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
JCGECore = { path = "../JCGECore" }
JCGERuntime = { path = "../JCGERuntime" }
