name = "JCGEOutput"
uuid = "d375a7b0-530a-4732-94fc-3dc39a3a1ffd"
authors = ["Riccardo Boero <ribo@nilu.no>"]
version = "0.0.0"

[deps]
JCGECore = "9fb9d605-0ed3-4980-82c1-f0874844db5d"
JCGERuntime = "cc244198-1562-43f7-ad75-589e1d675269"
DualSignals = "e4247b8d-50b5-41ef-b53d-f6e21a6bdac0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
JCGECore = { path = "../JCGECore" }
JCGERuntime = { path = "../JCGERuntime" }
