name = "JCGEImportData"
uuid = "8e499509-ec2a-45f1-ac19-e18611106d56"
authors = ["Riccardo Boero <ribo@nilu.no>"]
version = "0.0.0"

[deps]
JCGECalibrate = "52bcf1bb-6e19-4931-bbe4-0e0c79f03f49"
JCGECore = "9fb9d605-0ed3-4980-82c1-f0874844db5d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
JCGECalibrate = { path = "../JCGECalibrate" }
JCGECore = { path = "../JCGECore" }
